DROP TABLE IF EXISTS DonorInterests;
DROP TABLE IF EXISTS SalesItems;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Donations;
DROP TABLE IF EXISTS Donors;
